Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Tasken2.Models;

namespace Tasken2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/RegistrationController.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using Tasken2.DBContext;
using Tasken2.Models;

namespace Tasken2.Controllers
{
    public class RegistrationController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _host;
        public RegistrationController(AppDbContext context, IWebHostEnvironment host)
        {
            _context = context;
            _host = host;
        }
        public class Input
        {

            [Required]
            [StringLength(50)]
            public string firstName { get; set; } // الاسم الأول

            [Required]
            [StringLength(50)]
            public string lastName { get; set; } // الاسم الثاني

            [Required]
            [StringLength(14)]
            public string nationalID { get; set; } // رقم البطاقة الشخصية

            [Required]
            [StringLength(14)]
            [RegularExpression(@"^[0-9]{11}$", ErrorMessage = "Invalid Phone Number")]
            public string phoneNumber { get; set; } // رقم الهاتف

            [Required]
            [EmailAddress]
            public string email { get; set; } // البريد الإلكتروني

            [Required]
            [DataType(DataType.Password)]
            public string password { get; set; } // كلمة المرور

            [Required]
            [DataType(DataType.Password)]
            [Compare("password", ErrorMessage = "Passwords does not match.")]
            public string confirmPassword { get; set; } // تأكيد كلمة المرور
            public IFormFile img_file { get; set; }


        }
        [BindProperty]
        public Input input { get; set; }
        // GET: /Registration/
        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.message = "";
            return View();
        }

        // POST: /Registration/
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> IndexAsync()
        {
            Person person = new Person();


            if (input.img_file != null && input.img_file.Length > 0)
            {
                try
                {
                    // Get the wwwroot path
                    string uploadPath = Path.Combine(_host.WebRootPath, "images");
                    Directory.CreateDirectory(uploadPath);
                    // Generate a unique filename for the uploaded file
                    string newfilename = $"{Guid.NewGuid().ToString()}{Path.GetExtension(input.img_file.FileName)}";
                    string fileName = Path.Combine(uploadPath, newfilename);

                    // Save the file to the server
                    using (var fileStream = new FileStream(fileName, FileMode.Create))
                    {
                        input.img_file.CopyTo(fileStream);
                    }
                    person.nationalIdImage = Path.Combine("/images/", newfilename);
                    //TempData["ImagePath"] = Person.nationalIdImage;

                }
                catch (Exception ex)
                {
                    // Handle exceptions
                    return StatusCode(StatusCodes.Status500InternalServerError, "Error uploading file: " + ex.Message);
                }
            }


            if (ModelState.IsValid)
            {
                var existingPerson = _context.persons.SingleOrDefault(x => x.email == person.email);
                if (existingPerson != null)
                {
                    ViewBag.message = "User already exists";


                    return RedirectToAction("Index", "Login");
                }

                person = new Person
                {
                    firstName = input.firstName,
                    lastName = input.lastName,
                    nationalID = input.nationalID,
                    phoneNumber = input.phoneNumber,
                    email = input.email,
                    password = input.password,
                    confirmPassword = input.confirmPassword,
                    nationalIdImage = input.nationalID,
                    accountType = "user",
                    createdAt = DateTime.Now
                };


                _context.persons.Add(person);
                _context.SaveChanges();
                ViewBag.message = "Registration successful";
                return RedirectToAction("Index", "Login");
            }
            else
            {
                ViewBag.message = "Registration fail";
                return View(person);
            }


        }
    }
}

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml"; 
}

<style>
    li:hover {
        background-color: gray;
    }

    .textparagraph {
        font-family: Arial, Helvetica, sans-serif;
        text-align: center;
        position: absolute;
        top: 60%;
        left: 50%;
        width: 65%;
        transform: translate(-50%, -50%);
        color: white;
        font-size: large;
        font-style: italic;
    }

    .title {
        font-family: Arial, Helvetica, sans-serif;
        font-size: 5rem;
        font-style: italic;
        text-transform: uppercase;
    }

    .dec {
        margin: 20px 0px;
        letter-spacing: 3px;
        word-spacing: 8px;
        line-height: 50px;
    }

    .button1 {
        background-color: white;
        margin-right: 15px;
    }

    .button2 {
        background-color: #6195ff;
        color: #fff;
    }

    .home {
        height: 100vh;
        background-position: center;
        background-size: cover;
        background-repeat: no-repeat;
        position: relative;
    }

    .layerbLack {
        position: absolute;
        width: 100%;
        height: 100%;
        top: 0;
        left: 0;
        background-color: rgba(0, 0, 0, .4);
    }

    .main-button {
        min-width: 100px;
        padding: 15px 0;
        border: 0;
        border-radius: 20px;
        cursor: pointer;
        font-size: 18px;
        margin: 3px;
        text-align: center;
        display: inline-block;
        text-decoration: none; 
    }

        .main-button:hover {
            opacity: .8;
        }

    .hover-opacity {
        transition: opacity .5s;
    }
</style>

<div class="home">
    <div class="layerbLack"></div>
    <div class="textparagraph">
        <h1><p class="title">WELCOME</p></h1>

        <p class="dec">
            "اكتشف منزلك المثالي مع تسكين – حيث تتحقق أحلامك العقارية!"
        </p>

        <br />
        <br />
        <br />
        <span>

            “Discover the ideal with Taskin 
            – where your real 
                         estate dreams come true!”
        </span>


        <br />
        <br />
        <a href="@Url.Action("Index", "Login")" class="main-button hover-opacity button1">log in</a>
        <a href="@Url.Action("Index", "Registration")" class="main-button hover-opacity button2">sign up</a>
    </div>
</div>